name = "macro-tracker"
compatibility_date = "2026-05-13"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "macro_tracker"
database_id = "00000000-0000-0000-0000-000000000000"
preview_database_id = "macro_tracker"
